-- Expansion migration: legacy columns remain until APIs are migrated.
CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE agencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL, code VARCHAR(30) NOT NULL UNIQUE,
    contact_phone VARCHAR(30), is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(60) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO roles(code,name) VALUES ('EMS','EMS'),('NURSE','Nurse'),
    ('CHARGE_NURSE','Charge Nurse'),('DOCTOR','Doctor');
INSERT INTO departments(code,name) VALUES ('ER','Emergency Department');

ALTER TABLE users ADD COLUMN full_name VARCHAR(150),
    ADD COLUMN department_id INTEGER REFERENCES departments(id),
    ADD COLUMN agency_id INTEGER REFERENCES agencies(id),
    ADD COLUMN last_login_at TIMESTAMPTZ,
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
UPDATE users SET full_name=username, is_active=coalesce(is_active,true);
ALTER TABLE users ALTER COLUMN full_name SET NOT NULL,
    ALTER COLUMN is_active SET NOT NULL;
CREATE UNIQUE INDEX users_email_casefold_uq ON users(lower(email));
CREATE TABLE user_roles (
    user_id INTEGER NOT NULL REFERENCES users(id),
    role_id INTEGER NOT NULL REFERENCES roles(id),
    assigned_by INTEGER REFERENCES users(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(user_id,role_id)
);

ALTER TABLE patient_records ALTER COLUMN name DROP NOT NULL,
    ALTER COLUMN diagnosis DROP NOT NULL, ALTER COLUMN room DROP NOT NULL,
    ALTER COLUMN assigned_user_id DROP NOT NULL,
    ADD COLUMN date_of_birth DATE,
    ADD COLUMN sex VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN'
        CHECK(sex IN ('UNKNOWN','FEMALE','MALE','OTHER')),
    ADD COLUMN is_identity_verified BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE bed_registry ADD COLUMN department_id INTEGER REFERENCES departments(id),
    ADD COLUMN unavailable_reason TEXT,
    ADD COLUMN readiness_confirmed_at TIMESTAMPTZ,
    ADD COLUMN readiness_confirmed_by INTEGER REFERENCES users(id),
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
-- Naive legacy timestamps are retained verbatim. Backfill does not assume a timezone.
UPDATE bed_registry SET version=coalesce(version,1), status=coalesce(status,'AVAILABLE');
ALTER TABLE bed_registry ALTER COLUMN version SET NOT NULL, ALTER COLUMN status SET NOT NULL,
    ADD CONSTRAINT bed_status_ck CHECK(status IN ('AVAILABLE','RESERVED','OCCUPIED','TURNOVER','OUT_OF_SERVICE')),
    ADD CONSTRAINT bed_version_ck CHECK(version>0);

CREATE TABLE encounters (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_code VARCHAR(50) NOT NULL UNIQUE,
    patient_record_id INTEGER NOT NULL REFERENCES patient_records(id),
    department_id INTEGER NOT NULL REFERENCES departments(id),
    chief_complaint TEXT NOT NULL, diagnosis TEXT,
    reported_age_years SMALLINT CHECK(reported_age_years BETWEEN 0 AND 130),
    reported_acuity VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN'
        CHECK(reported_acuity IN ('UNKNOWN','ROUTINE','URGENT','CRITICAL')),
    status VARCHAR(20) NOT NULL CHECK(status IN ('EN_ROUTE','ARRIVED','IN_CARE','DISCHARGED','TRANSFERRED','CANCELLED')),
    interim_location VARCHAR(100), created_by INTEGER NOT NULL REFERENCES users(id),
    arrived_at TIMESTAMPTZ, arrival_confirmed_by INTEGER REFERENCES users(id),
    handoff_accepted_at TIMESTAMPTZ, handoff_accepted_by INTEGER REFERENCES users(id),
    care_started_at TIMESTAMPTZ, closed_at TIMESTAMPTZ, closed_by INTEGER REFERENCES users(id),
    closure_reason TEXT, transfer_destination VARCHAR(150), purge_after TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK((arrived_at IS NULL) = (arrival_confirmed_by IS NULL)),
    CHECK((handoff_accepted_at IS NULL) = (handoff_accepted_by IS NULL)),
    CHECK((status IN ('DISCHARGED','TRANSFERRED','CANCELLED')) = (closed_at IS NOT NULL)),
    CHECK((closed_at IS NULL) = (closed_by IS NULL)),
    CHECK((closed_at IS NULL) = (purge_after IS NULL)),
    CHECK(purge_after IS NULL OR purge_after >= closed_at),
    CHECK(status <> 'CANCELLED' OR nullif(btrim(closure_reason),'') IS NOT NULL),
    CHECK(status <> 'TRANSFERRED' OR nullif(btrim(transfer_destination),'') IS NOT NULL)
);
CREATE TABLE ems_transports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL UNIQUE REFERENCES encounters(id),
    agency_id INTEGER NOT NULL REFERENCES agencies(id), submitted_by INTEGER NOT NULL REFERENCES users(id),
    transport_reference VARCHAR(80) NOT NULL, unit_identifier VARCHAR(40),
    expected_arrival_at TIMESTAMPTZ NOT NULL, eta_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    treatments_administered TEXT, notes TEXT, acknowledged_at TIMESTAMPTZ,
    acknowledged_by INTEGER REFERENCES users(id), version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(agency_id,transport_reference),
    CHECK((acknowledged_at IS NULL) = (acknowledged_by IS NULL))
);
CREATE TABLE patient_observations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL REFERENCES encounters(id), recorded_by INTEGER NOT NULL REFERENCES users(id),
    observed_at TIMESTAMPTZ NOT NULL, source VARCHAR(20) NOT NULL CHECK(source IN ('EMS','HOSPITAL')),
    heart_rate_bpm SMALLINT CHECK(heart_rate_bpm>=0),
    systolic_bp_mmhg SMALLINT CHECK(systolic_bp_mmhg>=0),
    diastolic_bp_mmhg SMALLINT CHECK(diastolic_bp_mmhg>=0),
    respiratory_rate_per_min SMALLINT CHECK(respiratory_rate_per_min>=0),
    oxygen_saturation_pct NUMERIC(5,2) CHECK(oxygen_saturation_pct BETWEEN 0 AND 100),
    temperature_c NUMERIC(4,1), notes TEXT, corrects_observation_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(encounter_id,id),
    FOREIGN KEY(encounter_id,corrects_observation_id) REFERENCES patient_observations(encounter_id,id),
    CHECK(corrects_observation_id IS NULL OR corrects_observation_id<>id),
    CHECK(num_nonnulls(heart_rate_bpm,systolic_bp_mmhg,diastolic_bp_mmhg,
        respiratory_rate_per_min,oxygen_saturation_pct,temperature_c)>0 OR nullif(btrim(notes),'') IS NOT NULL)
);
CREATE TABLE bed_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL REFERENCES encounters(id), bed_id INTEGER NOT NULL REFERENCES bed_registry(id),
    assigned_by INTEGER NOT NULL REFERENCES users(id), assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ, ended_by INTEGER REFERENCES users(id), end_reason VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(ended_at IS NULL OR ended_at>=assigned_at),
    CHECK((ended_at IS NULL)=(ended_by IS NULL))
);
CREATE UNIQUE INDEX bed_assignments_active_bed_uq ON bed_assignments(bed_id) WHERE ended_at IS NULL;
CREATE UNIQUE INDEX bed_assignments_active_encounter_uq ON bed_assignments(encounter_id) WHERE ended_at IS NULL;
CREATE TABLE nurse_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL REFERENCES encounters(id), nurse_id INTEGER NOT NULL REFERENCES users(id),
    assigned_by INTEGER NOT NULL REFERENCES users(id), assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    accepted_at TIMESTAMPTZ, ended_at TIMESTAMPTZ, ended_by INTEGER REFERENCES users(id), end_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(ended_at IS NULL OR ended_at>=assigned_at),
    CHECK(accepted_at IS NULL OR accepted_at>=assigned_at), CHECK((ended_at IS NULL)=(ended_by IS NULL))
);
CREATE UNIQUE INDEX nurse_assignments_active_encounter_uq ON nurse_assignments(encounter_id) WHERE ended_at IS NULL;
CREATE TABLE preparation_tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL REFERENCES encounters(id), bed_id INTEGER REFERENCES bed_registry(id),
    title VARCHAR(200) NOT NULL CHECK(btrim(title)<>''), description TEXT,
    task_type VARCHAR(30) NOT NULL CHECK(task_type IN ('EQUIPMENT','ROOM','RESOURCE','OTHER')),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED')),
    is_required BOOLEAN NOT NULL DEFAULT true, assigned_to INTEGER REFERENCES users(id),
    assigned_department_id INTEGER REFERENCES departments(id), created_by INTEGER NOT NULL REFERENCES users(id),
    due_at TIMESTAMPTZ, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ,
    completed_by INTEGER REFERENCES users(id), blocked_reason TEXT, cancelled_reason TEXT,
    version INTEGER NOT NULL DEFAULT 1 CHECK(version>0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(encounter_id,id),
    CHECK(status<>'BLOCKED' OR nullif(btrim(blocked_reason),'') IS NOT NULL),
    CHECK(status<>'CANCELLED' OR nullif(btrim(cancelled_reason),'') IS NOT NULL),
    CHECK((status='COMPLETED')=(completed_at IS NOT NULL)),
    CHECK((completed_at IS NULL)=(completed_by IS NULL))
);
CREATE TABLE activity_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL REFERENCES encounters(id), actor_id INTEGER REFERENCES users(id),
    event_type VARCHAR(50) NOT NULL, message TEXT NOT NULL, reason TEXT,
    occurred_at TIMESTAMPTZ NOT NULL, recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_manual_entry BOOLEAN NOT NULL DEFAULT false, changes JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK(event_type<>'DOCTOR_OVERRIDE' OR (actor_id IS NOT NULL AND nullif(btrim(reason),'') IS NOT NULL))
);
CREATE TABLE alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id INTEGER NOT NULL REFERENCES encounters(id), task_id INTEGER,
    alert_type VARCHAR(50) NOT NULL, severity VARCHAR(20) NOT NULL CHECK(severity IN ('INFO','ACTION','URGENT')),
    message TEXT NOT NULL, deduplication_key VARCHAR(150) NOT NULL,
    resolved_at TIMESTAMPTZ, resolved_by INTEGER REFERENCES users(id), resolution_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY(encounter_id,task_id) REFERENCES preparation_tasks(encounter_id,id)
);
CREATE UNIQUE INDEX alerts_unresolved_key_uq ON alerts(deduplication_key) WHERE resolved_at IS NULL;
CREATE TABLE alert_recipients (
    alert_id INTEGER NOT NULL REFERENCES alerts(id), user_id INTEGER NOT NULL REFERENCES users(id),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(), seen_at TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ, escalation_due_at TIMESTAMPTZ, escalated_at TIMESTAMPTZ,
    PRIMARY KEY(alert_id,user_id)
);
CREATE TABLE request_idempotency (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id INTEGER NOT NULL REFERENCES users(id),
    request_key VARCHAR(100) NOT NULL, operation VARCHAR(100) NOT NULL, request_hash TEXT NOT NULL,
    response_status SMALLINT CHECK(response_status BETWEEN 100 AND 599), response_body JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(), expires_at TIMESTAMPTZ NOT NULL,
    UNIQUE(user_id,operation,request_key), CHECK(expires_at>created_at)
);
CREATE TABLE outbox_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), event_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50) NOT NULL, entity_id INTEGER NOT NULL, entity_version INTEGER NOT NULL CHECK(entity_version>0),
    payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count>=0), next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX encounters_department_status_idx ON encounters(department_id,status);
CREATE INDEX encounters_patient_idx ON encounters(patient_record_id);
CREATE INDEX encounters_purge_idx ON encounters(purge_after) WHERE closed_at IS NOT NULL;
CREATE INDEX transports_eta_idx ON ems_transports(expected_arrival_at);
CREATE INDEX observations_encounter_time_idx ON patient_observations(encounter_id,observed_at);
CREATE INDEX tasks_owner_status_idx ON preparation_tasks(assigned_to,status);
CREATE INDEX tasks_department_status_idx ON preparation_tasks(assigned_department_id,status);
CREATE INDEX events_encounter_time_idx ON activity_events(encounter_id,occurred_at);
CREATE INDEX recipients_user_idx ON alert_recipients(user_id,acknowledged_at);
CREATE INDEX nurse_active_idx ON nurse_assignments(nurse_id) WHERE ended_at IS NULL;
CREATE INDEX outbox_pending_idx ON outbox_events(next_attempt_at) WHERE published_at IS NULL;
CREATE INDEX idempotency_expiry_idx ON request_idempotency(expires_at);

-- Index all remaining referencing key prefixes for efficient FK checks/deletion.
DO $$ DECLARE r record; BEGIN
    FOR r IN SELECT c.conrelid::regclass AS tbl, c.conname,
        string_agg(quote_ident(a.attname), ',' ORDER BY u.ordinality) AS cols
        FROM pg_constraint c CROSS JOIN LATERAL unnest(c.conkey) WITH ORDINALITY AS u(attnum,ordinality)
        JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=u.attnum
        WHERE c.contype='f' AND c.connamespace='public'::regnamespace
        AND c.conrelid IN ('users'::regclass,'user_roles'::regclass,'bed_registry'::regclass,
          'encounters'::regclass,'ems_transports'::regclass,'patient_observations'::regclass,
          'bed_assignments'::regclass,'nurse_assignments'::regclass,'preparation_tasks'::regclass,
          'activity_events'::regclass,'alerts'::regclass,'alert_recipients'::regclass,'request_idempotency'::regclass)
        GROUP BY c.oid,c.conrelid,c.conname
    LOOP EXECUTE format('CREATE INDEX %I ON %s (%s)', 'fk_'||left(r.conname,45)||'_'||left(md5(r.conname),10), r.tbl, r.cols); END LOOP;
END $$;

CREATE FUNCTION hip_touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at=now(); RETURN NEW; END $$;
DO $$ DECLARE t text; BEGIN
    FOREACH t IN ARRAY ARRAY['departments','agencies','users','patient_records','bed_registry',
        'encounters','ems_transports','preparation_tasks','alerts']
    LOOP EXECUTE format('CREATE TRIGGER hip_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION hip_touch_updated_at()',t); END LOOP;
END $$;

-- Legacy registration still supplies username, but not full_name.
CREATE FUNCTION hip_default_full_name() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN IF NEW.full_name IS NULL THEN NEW.full_name=NEW.username; END IF; RETURN NEW; END $$;
CREATE TRIGGER hip_user_full_name BEFORE INSERT ON users FOR EACH ROW EXECUTE FUNCTION hip_default_full_name();
